### ISSUE TITLE
error on copy dependencies JS/CSS

### ISSUE THREAD

**Issue by dattaz** [kiwix/sotoki#25]
Traceback (most recent call last):
  File "sotoki.py", line 599, in <module>
    copytree('static', os.path.join('work', 'output'))
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/home/someone/dev/kiwix/sotoki/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'work/output'

=> cp -r static/* work/output/static/.  is a solution, we need to do this in python

**Comment by dattaz** [comment]
Close by #32
